### ISSUE TITLE
win+num shortcuts don't work

### ISSUE THREAD

**Issue by phly95** [CrypticButter/ButteryTaskbar#10]
Apps in taskbar with win+1, win+2, etc. shortcuts don't launch with shortcuts when taskbar is hidden.

**Comment by jstaro** [comment]
It works half the way if you press Win, Win+1, to start and switch to windows. The reverse, however, doesn't work (minimizing the window by pressing the hotkey again).

**Comment by LuisThiamNye** [comment]
@jstaro You might want to consider using a workaround, such as something from here: https://superuser.com/questions/189194/what-is-the-windows-hotkey-to-minimise-a-single-currently-active-window

**Comment by wiredmatt** [comment]
Can someone link me to where ButteryTaskbar messes with the Win key? It messed up all my shortcuts, specially the one I use to switch workspaces (Win {1..9}), I have already uninstalled it but it didn't revert that, I just want to know what's happening so I can get everything working again, thanks.

**Comment by LuisThiamNye** [comment]
@system32uwu That is strange — it should not do anything to the keybindings, since it just detects whether the Start menu is open. If you have not restarted since, perhaps do that or restart Windows Explorer. Otherwise I’m clueless.

**Comment by wiredmatt** [comment]
I restarted a couple times actually after disabling and uninstalling it, my only shortcut working is Win + O which I use to launch PowerToys Run, can you tell me the changes this makes to the registry? From what I read it does something with it, maybe I can try to revert it.

**Comment by wiredmatt** [comment]
Well I somehow got it working back again, but when I press Win {1...9} the start menu opens, which is not what I want to happen, what can I edit from the source code in order to permanently remove the bar? (I don't want to see it even if I'm pressing the Win key)

**Comment by LuisThiamNye** [comment]
@system32uwu You probably want to look at using something else.
There are various options here: https://superuser.com/questions/219605/how-to-completely-disable-the-windows-taskbar like [this script](https://superuser.com/a/1411754/949181)
and I also found this: https://www.eusing.com/hidewindows/bosskey.htm

**Comment by wiredmatt** [comment]
I managed to get the expected behavior launching ButteryTaskbar first and then the tiling window manager I'm using which captures keypress before ButteryTaskbar does.

**Comment by LuisThiamNye** [comment]
Buttery Taskbar 2 should fix this issue: https://github.com/LuisThiamNye/ButteryTaskbar2
