### ISSUE TITLE
Fullscreen windows resize at base

### ISSUE THREAD

**Issue by ghost** [CrypticButter/ButteryTaskbar#11]
With Buttery enabled, whenever a browser or program is set to fullscreen, all the edges are fine aside from the bottom (where my taskbar is set) which shows the resize cursor and allows me to resize and disable the fullscreen, toggling windowed mode. Thanks for making the program!

**Comment by ghost** [comment]
sorry, only seems to happen with the Min browser... any fixes?

**Comment by LuisThiamNye** [comment]
I'm afraid I don't have any solutions.

I'll close this as I do not think this is a problem with ButteryTaskbar
