### ISSUE TITLE
causes start menu to immediately close after hitting windows key, eventually it stops opening completely

### ISSUE THREAD

**Issue by mrvanderkam** [CrypticButter/ButteryTaskbar#18]
I've had buttery taskbar installed for over a year now with no problems. last week when I opened my start menu it was permanently scrolling through the menu.

in the command window I ran the following:

dism /online /cleanup-image /restorehealth
sfc /scannow

there were some errors that got repaired so I restarted my computer and it worked fine for a day, I uninstalled and reinstalled buttery taskbar.

now each time I restart my computer it works for a time and then eventually the start menu auto closes after opening and then it just stops opening altogether.

if I uninstall buttery taskbar I have no issues and I'm not tech savvy enough to know if its something else on my pc causing the problems. the only change I've made to my pc has been installing mods for monster hunter world.

**Comment by LuisThiamNye** [comment]
I'm no longer looking at issues for this program, but I have released version 2 of Buttery Taskbar. Feel free to try it out and see if you experience the same issues:

https://github.com/LuisThiamNye/ButteryTaskbar2
