### ISSUE TITLE
Broken after restarting Windows Explorer

### ISSUE THREAD

**Issue by ItsRady** [CrypticButter/ButteryTaskbar#2]
ButteryTaskbar no longer works when i restarted Windows Explorer, is there any way to fix this problem? Nvm i fixed it

**Comment by gplsource** [comment]
@ItsRady How do you fixed it? thx!

**Comment by gplsource** [comment]
I just figured out: register the app as a service. You can find the instructions at https://www.howtogeek.com/50786/using-srvstart-to-run-any-application-as-a-windows-service/

**Comment by LuisThiamNye** [comment]
Should be fixed in an update a while back
