### ISSUE TITLE
Taskbar won't render properly when more than one monitor is on

### ISSUE THREAD

**Issue by AbbieDoobie** [CrypticButter/ButteryTaskbar#20]
When I have one or more monitors on, the taskbar rarely will render properly, even if I restart Buttery Taskbar. It will work 1/10 attempts to open, and I haven't yet found a clear repro for the issue.

Notes:
1. At first I thought this was related to Explorer Patcher, but after uninstalling and restarting EP, this issue persists.
2. Killing Buttery Taskbar fixes the problem. Whether I use the mouse, or press windows key, the taskbar appears properly every time.
3. Issue does not occur with only 1 monitor on.
4. Found on Windows 11 22H2 22621.1702

Has anybody else ran into a similar issue? I believe development on this project has stopped, but I am hoping someone knows a fix. Thank you!

**Comment by Badgersenpai** [comment]
I am having the same issue. W10, extra monitor is connected via USB-C. As soon as second monitor is connected, buttery "opens" but it is just a large gap with no content. Tried disabling taskbar on all displays, restarting, basic troubleshooting to no avail. Hope someone has a fix as well!

**Comment by Badgersenpai** [comment]
After some more troubleshooting, it seems that this specific issue is happening when my taskbar is on the same side that bleeds into my second display. I.e. my second display is oriented to the left of my primary monitor and my taskbar is also oriented to the left. If I move the taskbar orientation away from my second monitor, buttery works just fine.

**Comment by LuisThiamNye** [comment]
I have seen this issue myself.

Try version 2 and see if that is better: https://github.com/LuisThiamNye/ButteryTaskbar2
