### ISSUE TITLE
Dosn´t work autostart - WIndows 10

### ISSUE THREAD

**Issue by kllr007** [CrypticButter/ButteryTaskbar#4]
Hi, great app. But I have problem with windows 10 if I set it to autostart, it indeed autostart (it shows in tray etc) but doesnt work. I need to quit it and start manualy - then it works... Is there any way to make it "auto start" ?

**Comment by gplsource** [comment]
Install it as a service. I put a link before.

**Comment by kllr007** [comment]
I saw that comment but it doenst work for me, cant start service as i says it was terminated.

**Comment by LuisThiamNye** [comment]
I've had this problem. Is it still an issue in the latest version (1.2.2.1)?

**Comment by LuisThiamNye** [comment]
Buttery Taskbar has been succeeded by Buttery Taskbar 2 for which you set up the auto-start yourself: https://github.com/LuisThiamNye/ButteryTaskbar2
