### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Theblockbuster1** [CrypticButter/ButteryTaskbar#5]
I've tried installing with administrator but I still get this error: [https://i.imgur.com/oD9aUyv.png](https://i.imgur.com/oD9aUyv.png)
When you press 'Details...' it comes up with a notepad with this: [https://pastebin.com/WkpdqD0Y](https://pastebin.com/WkpdqD0Y)

**Comment by ghost** [comment]
i got a cant install issue with this in the notepad:
* Activation of https://raw.githubusercontent.com/CrypticButter/ButteryTaskbar/master/CrypticButter.ButteryTaskbar/publish/CrypticButter.ButteryTaskbar.application resulted in exception. Following failure messages were detected:
+ The referenced assembly is not installed on your system. (Exception from HRESULT: 0x800736B3)

what assembly is required to download?

**Comment by LuisThiamNye** [comment]
@giffur maybe try installing .NET Framework 4.6.1 https://www.microsoft.com/en-gb/download/details.aspx?id=49981 if you do not already have it installed.

**Comment by ghost** [comment]
@LuisThiamNye ran the application and got this:
.NET Framework 4.6.1 or a later update is already installed on this computer.

**Comment by LuisThiamNye** [comment]
@giffur In that case, I'm afraid I'm not sure how to solve the problem.

**Comment by carson-000** [comment]
This error is still ongoing for me. Tried everything. I wonder when this is going to be updated...

**Comment by LuisThiamNye** [comment]
@ThatNoobYeetR wonder no more: it's not going to be updated.

1. I haven't touched C# / this project in years.
2. It works fine when I install it on Windows 10 (I do not expect it to work on other versions of Windows).
3. I do not know how to reproduce the issue, and there's not a lot of information to work with.
4. I do not use the application myself nowadays.

Of course, I welcome anyone who is kind enough to submit any pull requests to fix any issues.

**Comment by carson-000** [comment]
Oh, ok. Makes sense.

**Comment by ghost** [comment]
[buttery.log](https://github.com/CrypticButter/ButteryTaskbar/files/7542261/buttery.log)
this is the error file i get with as many details as the program offers

**Comment by ghost** [comment]
is there something regarding installing an assembly similar to:
`<dependentAssembly dependencyType="install" codebase="Application Files\CrypticButter.ButteryTaskbar_1_2_2_1\CrypticButter.ButteryTaskbar.exe.manifest" size="9477">`
via [sourced code](https://raw.githubusercontent.com/CrypticButter/ButteryTaskbar/master/CrypticButter.ButteryTaskbar/publish/CrypticButter.ButteryTaskbar.application) ?
if so, any way to manually install the packaged assembly file or redirect the program to install from another source?

**Comment by sisrfeng** [comment]
Is this repo alive? Can't install

**Comment by LuisThiamNye** [comment]
*Introducing Buttery Taskbar 2 where you'll never have to deal with .NET/C# craziness again!*

https://github.com/LuisThiamNye/ButteryTaskbar2

You can't fail to install a program that doesn't have an installer!
