### ISSUE TITLE
Hotkey to Toggle Disable/Enable

### ISSUE THREAD

**Issue by ClementineAccount** [CrypticButter/ButteryTaskbar#6]
This will allow being able to set the state of the desktop from Taskbar Enabled to Taskbar Disabled for different situations, allowing further customization. Disable is already a feature and I would simply like a configurable hotkey to turn it on instead of clicking.

**Comment by LuisThiamNye** [comment]
I have just released Buttery Taskbar 2 which has this feature: https://github.com/LuisThiamNye/ButteryTaskbar2
