### ISSUE TITLE
Can't use Task Scheduler to run the app to make it run faster (highest priority) when windows boot

### ISSUE THREAD

**Issue by WilliamLeGod** [CrypticButter/ButteryTaskbar#7]
Hi!
Im very greatful that I found this app and really appreciate your work. It's been a life changer for me after using this app!
I have been using it for awhile and I do want to make it more suitable for my needs
I notice whenever I boot into windows, It takes a few seconds to trigger the app and that causes an annoying windows startup screen for a few seconds for my eyes so I decided to boot it up faster by using Task Scheduler and set run this program at highest priority to make it boot faster (like within 1 second when windows screen show up) But it doesn't start at all :( (I even find and target the .exe file of this app but same issue)
I tried test other programs to run at highest priority in Task Scheduler and they all work perfectly fine

So my question is: Is there any way to run this app in Task Scheduler to make it boot within 1 second at windows startup OR by any chance you could include an option in the app to set at highest priority startup?

I'm happy to donate if possible as I really really need this to perfect my computer setup

I'm looking forward to hearing from you soon!

Best regards,

William

**Comment by LuisThiamNye** [comment]
While this software is not my primary focus, I did try looking into this a bit. This gave me good results (instant startup):

- Create a task in task scheduler to start on login. The program it should run is `cmd`.
- Put this in "add arguments", giving your correct username:
`/c "C:\Users\<USERNAME>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Cryptic Butter\Buttery Taskbar.appref-ms"`
![image](https://user-images.githubusercontent.com/41270840/91299047-f209df80-e798-11ea-9f52-7a25cd596941.png)
- If using a laptop, make sure this is unticked in the "conditions" tab:
![image](https://user-images.githubusercontent.com/41270840/91299507-9e4bc600-e799-11ea-839c-c18b3ec7013f.png)
- In the "general" tab
![image](https://user-images.githubusercontent.com/41270840/91299609-cdface00-e799-11ea-8f23-64b2d961af67.png)
The program does not need elevated privileges and the "hidden" setting has no effect when running as your user account.

Also, make sure you have "start with windows" **unchecked** when right-clicking the Buttery Taskbar tray icon.

**Comment by WilliamLeGod** [comment]
Thank you so much for your help and it works!
Still there is 0.5 second the CMD window shows up at startup, could there be anyway to perform this cmd hidden/visible since you mention "Hidden" feature in Task scheduler doesn't work?. I just want to make it as clean as possible :( 
 Again, thanks so much for spend your precious time to help me since you are busy with other projects.

**Comment by LuisThiamNye** [comment]
Get task scheduler to run a Visual Basic or PowerShell script which in turn runs the program at
`"C:\Users\<USERNAME>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Cryptic Butter\Buttery Taskbar.appref-ms"`
https://winaero.com/blog/run-a-program-hidden-in-windows-10/
https://superuser.com/questions/62525/run-a-batch-file-in-a-completely-hidden-way
