### ISSUE TITLE
How to remove that white border?

### ISSUE THREAD

**Issue by SymphonySimper** [CrypticButter/ButteryTaskbar#9]

**Comment by LuisThiamNye** [comment]
This needs more information.

**Comment by senyehor** [comment]
![image](https://user-images.githubusercontent.com/78546473/175771811-4824a28c-f184-4c7a-b93d-b1593367511e.png)
Here is what this white line looks like, it appear on the side where taskbar is at (win 21h2). I tried on another win10 computer and got the same results. Though, some application (Chrome) do not have this line, but most (Telegram, PyCharm, FileExplorer) do have.
P.S.
Apparently, it is not shown at screenshots, but was shown when I casted my screen at discord.

**Comment by LuisThiamNye** [comment]
That sounds like it might be the two-pixel gap that the taskbar leaves behind. When the program hides the taskbar via the Windows API, that gap still remains and app windows usually don't occupy it.

(Even when the taskbar is set to auto-hide, it still occupies a slither of screen space along the edge of the screen which is used to detect the cursor)

**Comment by senyehor** [comment]
Yes I know that it is, but I am more interested in fixing it, rather that knowing it`s nature) Do u use this app (ButteryTaskbar) and have no weir white lines?

**Comment by LuisThiamNye** [comment]
I've been primarily using macOS for the last 3 years so it had not made any sense for me to work on it.

The challenge involves browsing the Win32 API and see if it provides anything that could remove the gap.

As always, I welcome contributions if anyone is up for the task.
